name: tayyorr_app
description: "tayyorr.uz — talabalar uchun platforma"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # tarmoq
  dio: ^5.7.0

  # Google bilan kirish
  google_sign_in: ^6.2.2

  # holat boshqaruvi (BLoC)
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # mahalliy saqlash
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.2

  # UI
  google_fonts: ^6.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
